import { and, desc, eq, like } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { appSettings, authSessions, estimateItems, estimates, pricingRules, users, type InsertUser } from "../drizzle/schema";
import { ENV } from "./_core/env";

let database: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!database && process.env.DATABASE_URL) { try { database = drizzle(process.env.DATABASE_URL); } catch { database = null; } } return database; }
export async function upsertUser(user: InsertUser) { if (!user.openId) return; const db = await getDb(); if (!db) return; await db.insert(users).values({ openId: user.openId, name: user.name ?? null, email: user.email ?? null, loginMethod: user.loginMethod ?? null, role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "user"), lastSignedIn: user.lastSignedIn ?? new Date() }).onDuplicateKeyUpdate({ set: { name: user.name ?? null, email: user.email ?? null, lastSignedIn: user.lastSignedIn ?? new Date() } }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); return db ? (await db.select().from(users).where(eq(users.openId, openId)).limit(1))[0] : undefined; }
export async function getCredentialUser(username: string) { const db = await getDb(); return db ? (await db.select().from(users).where(and(eq(users.username, username), eq(users.active, true))).limit(1))[0] : undefined; }
export async function getUserById(id: number) { const db = await getDb(); return db ? (await db.select().from(users).where(eq(users.id, id)).limit(1))[0] : undefined; }
export async function listAuthorizedUsers() { const db = await getDb(); return db ? db.select({ id: users.id, username: users.username, name: users.name, role: users.role, active: users.active, createdAt: users.createdAt, lastSignedIn: users.lastSignedIn }).from(users).where(eq(users.loginMethod, "password")).orderBy(desc(users.createdAt)) : []; }
export async function getAuthorizedUserCount() { return (await listAuthorizedUsers()).length; }
export async function listPricingRules(includeInactive = false) { const db = await getDb(); if (!db) return []; return includeInactive ? db.select().from(pricingRules).orderBy(pricingRules.sortOrder, pricingRules.productName, pricingRules.places, pricingRules.itemType, pricingRules.fabric) : db.select().from(pricingRules).where(eq(pricingRules.active, true)).orderBy(pricingRules.sortOrder, pricingRules.productName, pricingRules.places, pricingRules.itemType, pricingRules.fabric); }
export async function getPricingRuleById(id: number) { const db = await getDb(); return db ? (await db.select().from(pricingRules).where(eq(pricingRules.id, id)).limit(1))[0] : undefined; }
export async function getSessionUserByTokenHash(hash: string) { const db = await getDb(); return db ? (await db.select({ user: users, expiresAt: authSessions.expiresAt }).from(authSessions).innerJoin(users, eq(authSessions.userId, users.id)).where(and(eq(authSessions.tokenHash, hash), eq(users.active, true))).limit(1))[0] : undefined; }
export async function createSessionRecord(tokenHash: string, userId: number, expiresAt: Date) { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível."); await db.insert(authSessions).values({ tokenHash, userId, expiresAt }); }
export async function removeSessionRecord(tokenHash: string) { const db = await getDb(); if (db) await db.delete(authSessions).where(eq(authSessions.tokenHash, tokenHash)); }
export async function touchUserSignIn(userId: number) { const db = await getDb(); if (db) await db.update(users).set({ lastSignedIn: new Date() }).where(eq(users.id, userId)); }
export async function listEstimates(filters: { quoteNumber?: number; customerName?: string }) { const db = await getDb(); if (!db) return []; const condition = filters.quoteNumber ? eq(estimates.id, filters.quoteNumber) : filters.customerName ? like(estimates.customerName, `%${filters.customerName}%`) : undefined; return db.select().from(estimates).where(condition).orderBy(desc(estimates.createdAt)); }
export async function getEstimateWithItems(id: number) { const db = await getDb(); if (!db) return undefined; const estimate = (await db.select().from(estimates).where(eq(estimates.id, id)).limit(1))[0]; if (!estimate) return undefined; const items = await db.select().from(estimateItems).where(eq(estimateItems.estimateId, id)).orderBy(estimateItems.id); return { estimate, items }; }
export async function listSettings() { const db = await getDb(); return db ? db.select().from(appSettings) : []; }
